#!/bin/sh
export WORKDIR=/home/andrea/Alabs/Devel/mod/
source ../mod-plugin-builder/local.env moddwarf-new
echo "Building modtools library" 
make -C mod-ui/utils clean
make -C mod-ui/utils
echo "Building mod-host"
make -C mod-host clean
make -C mod-host
#make -C mod-host PREFIX=/usr DESTDIR=$(pwd)/mod-host/install install
