#!/bin/bash

# source global configs
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "$SCRIPT_DIR/config.sh"

if [ "$1" != "moddwarf-new" ] && [ "$1" != "modduox-new" ] && [ "$1" != "tag" ]
  then
	echo "Invalid platform supplied"
	echo "    available platforms: moddwarf-new | modduox-new"
	echo "    use: create-image <platform> <command> ..."
	exit 1
fi

if [ $1 != "tag" ] && [ "$2" != "update" ] && [ "$2" != "build" ] && [ "$2" != "release" ]
  then
	echo "Invalid command supplied"
	echo "    available commands: update | build | tag | release"
	exit 1
fi

if [[ "$2" == "build" || "$2" == "release" ]] && [ -z "$3" ]
  then
	echo "No tar base image supplied"
	echo "    usage: create-image <platform> build <base-image-name.tar> <custom-version-name>"
	echo "    example: create-image moddwarf-new build moddwarf-1.0.0.tar alabs42"
	exit 1
fi
if [[ "$2" == "build" || "$2" == "release" ]] && [ -z "$4" ]
  then
	echo "No version name supplied"
	echo "    usage: create-image <platform> build <base-image-name.tar> <custom-version-name>"
	echo "    example: create-image moddwarf-new build moddwarf-1.0.0.tar alabs42"
	exit 1
fi

if [ "$1" = "tag" ] && [ -z "$2" ]
  then
	echo "No tar base image supplied"
	echo "    usage: create-image tag <custom-version-name>"
	echo "    example: create-image tag alabs42"
	exit 1
fi

COMMAND=$2
TAR_BASE_IMAGE=$3
TAG_NAME=$2
TAG_VERSION=${TAG_NAME#alabs}
VERSION=$4
filename=$(basename -- "$TAR_BASE_IMAGE")
TAR_NAME="${filename%.*}"
IMAGE_NAME="$TAR_NAME-$VERSION"
VER_IMAGE=${TAR_NAME#*-}
VER_BASE=${VER_IMAGE%.*}
VER_BASE_BUILD=${VER_IMAGE:${#VER_BASE}+1:10}

if [ "$1" = "tag" ]
  then
	echo "TAGGING GIT REPOSITORIES"
	git -C $ALABS_ROOT/mod-dwarf-controller tag -a $TAG_NAME -m "aLabs release $TAG_VERSION"
	git -C $ALABS_ROOT/mod-ui tag -a $TAG_NAME -m "aLabs release $TAG_VERSION"
	git -C $ALABS_ROOT/mod-host tag -a $TAG_NAME -m "aLabs release $TAG_VERSION"
	git tag -a $TAG_NAME -m "aLabs release $TAG_VERSION"
	exit $?
fi

# STARTING CREATE IMAGE


echo 'ALABS MOD IMAGE BUILDER'
echo '    platform.........: ' $PLATFORM
echo '    base image.......: ' $IMAGE_NAME
echo '    base image vers..: ' $VER_IMAGE
echo '    source dir.......: ' $ALABS_ROOT
echo '    custom build.....: ' $VERSION
echo '    custom firmware..: ' $FIRMWARE_DIR
echo ' '
read -p 'Press ENTER key to start' PROCEED
echo ' '

if [[ "$2" == "update" || "$2" == "release" ]]
  then
	echo "Update GIT submodules"
	git submodule update --init --remote --recursive
	git add $ALABS_ROOT/mod-dwarf-controller
	git add $ALABS_ROOT/mod-ui
	git add $ALABS_ROOT/mod-host

	echo 'Update dependencies'
	if [ ! -d $ALABS_ROOT/deps/cc-master ]; then
		git clone --depth 1 --branch master https://github.com/mod-audio/cc-master.git $ALABS_ROOT/deps/cc-master
	fi

	# exit if command is update, otherwise continue to build the image
	if [ "$2" = "update" ]; then
		echo 'Done'
		exit $?
	fi
fi

echo -n 'Source dir sanity check...'
if [ -z $IMAGE_NAME ]; then
	echo 'image name is empty'
	exit 1
fi
# check mod ui sources
if [ ! -d $ALABS_ROOT/mod-ui ]; then
	echo '    [ERR] MOD-UI sources not found in ' $ALABS_ROOT'/mod-ui'
	exit 1
fi

if [ $PLATFORM = "moddwarf-new" ]; then
	echo '    Building custom HMI firmware from ' $FIRMWARE_DIR

	FIRMWARE_DIR=$ALABS_ROOT/mod-dwarf-controller
	CONTROLLER_GIT_HASH=`git -C $FIRMWARE_DIR rev-parse HEAD`
	CONTROLLER_GIT_DATE=`git -C $FIRMWARE_DIR show --no-patch --format=%cd HEAD`
	if [ ! $? -eq 0 ]; then
		exit 1
	fi

	echo 'Rebuilding controller firmware'

	cd $FIRMWARE_DIR
	make clean
	make moddwarf
	if [ ! $? -eq 0 ]; then
		echo 'Fail to build controller firmware'
		exit 1
	fi

else
	echo '    Custom HMI firmware sources not supported for this platform, using prebuilt firmware'
fi


STARLESS_GIT_HASH=`git -C $ALABS_ROOT rev-parse HEAD`

echo 'passed'
cd $ALABS_ROOT

echo 'Building mod binaries using docker build enviroment'
bash docker-build $PLATFORM
if [ ! $? -eq 0 ]; then
	echo 'Fail to build modtools library'
	exit 1
fi

echo 'Cleaning up'
rm -rf $IMAGE_NAME

echo 'Setup dir'
mkdir $IMAGE_NAME

echo 'Extracting original tar image: ' $TAR_BASE_IMAGE
tar -xf $TAR_BASE_IMAGE -C $IMAGE_NAME

echo 'Extracting original system image: ' $TAR_BASE_IMAGE
BASE_SYSTEM_DIR=$IMAGE_NAME/tmp/system
mkdir -p $BASE_SYSTEM_DIR
sudo tar -xpf $IMAGE_NAME/system.tar.xz -C $BASE_SYSTEM_DIR

# fix console device
#sudo mknod $BASE_SYSTEM_DIR/./dev/console c 5 1
#sudo chmod 622 $BASE_SYSTEM_DIR/./dev/console

if [ -z $IMAGE_NAME ]; then
	echo 'not doing chown IMAGE_NAME is empty'
fi
rm -f $IMAGE_NAME/system.tar.xz 

echo 'Removing original files'
sudo rm -rf $BASE_SYSTEM_DIR/usr/lib/python3.4/site-packages/modtools/*
sudo rm -rf $BASE_SYSTEM_DIR/usr/lib/python3.4/site-packages/mod/*
sudo rm -rf $BASE_SYSTEM_DIR/usr/share/mod/html/*

echo 'Copying new files: mod-ui'
sudo cp -ar $ALABS_ROOT/mod-ui/utils/libmod_utils.so $BASE_SYSTEM_DIR/usr/lib/python3.4/site-packages/modtools/
sudo cp -ar $ALABS_ROOT/mod-ui/modtools/* $BASE_SYSTEM_DIR/usr/lib/python3.4/site-packages/modtools/
sudo cp -ar $ALABS_ROOT/mod-ui/mod/* $BASE_SYSTEM_DIR/usr/lib/python3.4/site-packages/mod/
sudo cp -ar $ALABS_ROOT/mod-ui/html/* $BASE_SYSTEM_DIR/usr/share/mod/html/

# remove some unused dirs
sudo rm -rf $BASE_SYSTEM_DIR/usr/lib/python3.4/site-packages/mod/old
sudo rm -rf $BASE_SYSTEM_DIR/usr/lib/python3.4/site-packages/mod/knob-utils
sudo rm -rf $BASE_SYSTEM_DIR/usr/lib/python3.4/site-packages/mod/__pycache__/*
sudo rm -rf $BASE_SYSTEM_DIR/usr/lib/python3.4/site-packages/modtools/__pycache__/*

echo 'Copying new files: mod-host'
sudo cp -ar $ALABS_ROOT/mod-host/mod-host $BASE_SYSTEM_DIR/usr/bin
sudo cp -ar $ALABS_ROOT/mod-host/mod-host.so $BASE_SYSTEM_DIR/usr/lib/jack/
sudo cp -ar $ALABS_ROOT/mod-host/fake-input.so $BASE_SYSTEM_DIR/usr/lib/jack/
sudo cp -ar $ALABS_ROOT/mod-host/mod-monitor.so $BASE_SYSTEM_DIR/usr/lib/jack/

if [ -d $ALABS_ROOT/keys ]; then
	echo 'Copying alabs api keys'
	sudo cp -ar $ALABS_ROOT/keys/* $BASE_SYSTEM_DIR/usr/share/mod/keys/
fi

echo 'Update mod-os release'

if [ $PLATFORM = "moddwarf-new" ]; then
	echo 'Adding firmware'
	cp -ar $FIRMWARE_DIR/out/mod-dwarf-controller.bin $IMAGE_NAME/

	# copy firmware and debug symbols in the new image
	sudo chmod o+w $BASE_SYSTEM_DIR/usr/share/mod/controller
	sudo chmod o+w $BASE_SYSTEM_DIR/usr/share/mod/controller/mod-dwarf-controller.bin
	sudo chmod o+w $BASE_SYSTEM_DIR/usr/share/mod/controller/version
	cp $FIRMWARE_DIR/out/mod-dwarf-controller.bin $BASE_SYSTEM_DIR/usr/share/mod/controller/mod-dwarf-controller.bin
	cp $FIRMWARE_DIR/out/mod-dwarf-controller.dbg $BASE_SYSTEM_DIR/usr/share/mod/controller/mod-dwarf-controller.dbg
	cat > $BASE_SYSTEM_DIR/usr/share/mod/controller/version <<EOL
${CONTROLLER_GIT_HASH}
EOL

	if [ ! $? -eq 0 ]; then
		echo 'Cannot copy mod warf controller firmware'
		exit 1
	fi

	echo 'Creating versions file'
	# controller firmware
	CONTROLLER_DATE=`date '+%Y %b %d %H:%M:%S'`
	sudo chmod o+w $BASE_SYSTEM_DIR/etc/mod-release/controller 
	cat > $BASE_SYSTEM_DIR/etc/mod-release/controller <<EOL
generated=${CONTROLLER_DATE} at ${HOSTNAME}
revision=${CONTROLLER_GIT_HASH}
EOL

	sudo chmod o-w $BASE_SYSTEM_DIR/etc/mod-release/controller 
fi

# os release
sudo chmod o+w $BASE_SYSTEM_DIR/etc/mod-release/release
cat > $BASE_SYSTEM_DIR/etc/mod-release/release<<EOL
${VER_IMAGE}-${VERSION}
EOL
sudo chmod o-w $BASE_SYSTEM_DIR/etc/mod-release/release

# os system
SYSTEM_DATE=`date '+%Y %b %d %H:%M:%S'`
sudo chmod o+w $BASE_SYSTEM_DIR/etc/mod-release/system
cat > $BASE_SYSTEM_DIR/etc/mod-release/system<<EOL
generated=${SYSTEM_DATE} at ${HOSTNAME}
revision=${STARLESS_GIT_HASH}
EOL
sudo chmod o-w $BASE_SYSTEM_DIR/etc/mod-release/system

sudo chmod o+w $IMAGE_NAME/VERSIONS
cat > $IMAGE_NAME/VERSIONS  <<EOL
version=${VER_BASE}
build=${VER_BASE_BUILD}-${VERSION}
version.build=${VER_IMAGE}-${VERSION}
label=
restore=48de0f238fdb1ff138a734a1272c
system=${STARLESS_GIT_HASH}
controller=${CONTROLLER_GIT_HASH}
platform=moddwarf
EOL
sudo chmod o-w $IMAGE_NAME/VERSIONS

echo 'Repacking system distribution' 
sudo tar cpfJ $IMAGE_NAME/system.tar.xz -C $BASE_SYSTEM_DIR .

echo 'Calculating checksum'
rm -f $IMAGE_NAME/SHA1SUMS
if [ $PLATFORM = "moddwarf-new" ]; then
	sha1sum $IMAGE_NAME/mod-dwarf-controller.bin | sed "s/$IMAGE_NAME\///" >> $IMAGE_NAME/SHA1SUMS
else
	# standard duox firmaware
	sha1sum $IMAGE_NAME/mod-duox-controller.bin | sed "s/$IMAGE_NAME\///" >> $IMAGE_NAME/SHA1SUMS
	sha1sum $IMAGE_NAME/mod-duox-le-controller.bin | sed "s/$IMAGE_NAME\///" >> $IMAGE_NAME/SHA1SUMS
fi
sha1sum $IMAGE_NAME/restore.tar.xz | sed "s/${IMAGE_NAME}\///" >> $IMAGE_NAME/SHA1SUMS
sha1sum $IMAGE_NAME/system.tar.xz | sed "s/${IMAGE_NAME}\///" >> $IMAGE_NAME/SHA1SUMS
sha1sum $IMAGE_NAME/VERSIONS | sed "s/${IMAGE_NAME}\///" >> $IMAGE_NAME/SHA1SUMS

echo 'Cleanup image folder'
sudo rm -rf $IMAGE_NAME/tmp

echo 'Packing image file'
rm -f $IMAGE_NAME.tar
tar cf $IMAGE_NAME.tar -C $IMAGE_NAME .
sha1sum $IMAGE_NAME.tar > $IMAGE_NAME.tar.sha1

echo 'Cleanup'
sudo rm -rf $IMAGE_NAME

echo 'DONE!'

exit 0

